baseURL = "/"
locale = "en-us"
title = "Jamie Meggas"

disableKinds = ["taxonomy", "term", "rss"]

[params]
  role = "Brand & identity designer"
  email = "jmeggas42@gmail.com"

[markup.goldmark.renderer]
  unsafe = true
